version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: node.docker
      args:
        - version=${NODE_VERSION}
    image: trubiv/latest_node_app
    container_name: my_map_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
